// Curated token pools for the body-for-visits artwork.
// Themes: visitation, enclosure, attention, request/response, memory,
// compression, witness, address, body, signal, latency, residue, consent,
// disappearance, archive, surface, server, return, threshold.
// Not buzzword soup. Tokens carry the work's tone.

export const BUCKETS = {
  openings: [
    "here", "again", "still", "meanwhile", "before that", "elsewhere",
    "since you arrived", "between requests", "in the margin", "under the cache",
    "now", "once more", "afterward", "already", "soon", "later", "earlier",
    "beforehand", "in passing", "in transit", "in the open", "in the record",
    "in the log", "in the queue", "at the threshold", "at the edge", "at first",
    "at last", "at once", "by now", "by then", "for now", "for a while",
    "from here", "from there", "just now", "of late", "on arrival", "on return",
    "on the surface", "on the record", "over and over", "past that",
    "since then", "thereafter", "until now", "within reach", "without warning",
    "after the request", "after the answer", "before the answer",
    "beneath the page", "between the lines", "between answers",
    "in the interval", "in the meantime", "in the residue", "in the corridor",
    "in the anteroom", "near the threshold", "under observation",
    "while you wait", "while it loads", "after the fold", "before the fold",
    "off the record", "somewhere else", "here again", "still here", "even now",
    "ever since", "far from here", "close by", "somewhere near",
    "deep in the archive", "at the far end", "mid-request", "between visits",
    "after the pause", "before the pause", "once arrived", "having waited",
    "when you came", "when it began", "where it began", "again and again",
    "slowly now", "quietly here", "faintly", "barely", "almost", "not yet",
    "no longer", "somewhere", "afterward still", "long after",
  ],
  nouns: [
    "visitor", "witness", "threshold", "cache", "archive", "residue", "surface",
    "server", "room", "request", "response", "signal", "latency", "body",
    "column", "breath", "address", "hand", "page", "record", "log", "trace",
    "echo", "mirror", "window", "door", "hallway", "corridor", "anteroom",
    "chamber", "ledger", "index", "margin", "footnote", "document", "packet",
    "payload", "header", "cursor", "pointer", "handshake", "session", "token",
    "fragment", "remainder", "interval", "pause", "silence", "hum", "current",
    "pulse", "thread", "queue", "buffer", "gateway", "port", "channel", "node",
    "edge", "lattice", "grid", "frame", "pane", "glass", "wall", "floor",
    "ceiling", "corner", "seam", "hinge", "latch", "key", "lock", "gate",
    "fence", "border", "perimeter", "boundary", "limit", "horizon", "distance",
    "proximity", "presence", "absence", "name", "shadow", "reflection",
    "imprint", "fingerprint", "stain", "mark", "watermark", "seal", "stamp",
    "receipt", "manifest", "inventory", "register", "count", "tally",
    "attention", "regard", "notice", "glance", "gaze", "observer", "reader",
    "recipient", "sender", "courier", "messenger", "host", "guest", "tenant",
    "occupant", "stranger", "crowd", "network", "circuit", "wire", "cable",
    "conduit", "vessel", "container", "enclosure", "vault", "repository",
    "stack", "shelf", "drawer", "folder", "file", "transcript", "account",
    "statement", "report", "dispatch", "annotation", "gloss", "aside",
    "parenthesis", "ellipsis", "omission", "gap", "void", "vacancy",
    "weight", "mass", "density", "texture", "grain", "dust", "sediment",
    "layer", "stratum", "membrane", "skin", "husk", "shell", "casing",
  ],
  verbs: [
    "arrives", "lingers", "returns", "folds", "holds", "attends", "forgets",
    "remembers", "compresses", "answers", "withholds", "passes through",
    "marks", "keeps", "releases", "waits", "watches", "listens", "notices",
    "records", "logs", "registers", "counts", "numbers", "names", "unnames",
    "signs", "witnesses", "observes", "regards", "considers", "dwells",
    "remains", "stays", "persists", "endures", "fades", "dims", "dissolves",
    "disappears", "vanishes", "recedes", "withdraws", "departs", "leaves",
    "exits", "enters", "approaches", "crosses", "passes", "traverses",
    "threads", "drifts", "wanders", "circles", "repeats", "recurs", "resumes",
    "continues", "proceeds", "begins", "opens", "closes", "seals", "locks",
    "unlocks", "gathers", "collects", "accumulates", "stores", "archives",
    "files", "indexes", "sorts", "orders", "arranges", "assembles", "unfolds",
    "expands", "contracts", "narrows", "widens", "settles", "rests", "pauses",
    "hesitates", "falters", "breathes", "hums", "echoes", "reflects", "mirrors",
    "doubles", "halves", "divides", "joins", "binds", "frees", "admits",
    "refuses", "declines", "consents", "permits", "allows", "accepts",
    "receives", "gives", "offers", "extends", "reaches", "touches", "grazes",
    "traces", "follows", "leads", "carries", "bears", "transmits", "relays",
    "forwards", "delivers", "repays", "recalls", "retains", "discards",
    "erases", "overwrites", "revises", "completes", "abandons", "expires",
  ],
  adjectives: [
    "quiet", "attentive", "partial", "unfinished", "legible", "narrow", "slow",
    "late", "present", "consented", "seen", "archived", "nameless", "returning",
    "silent", "still", "faint", "dim", "pale", "thin", "sparse", "brief",
    "fleeting", "momentary", "transient", "provisional", "tentative",
    "uncertain", "hesitant", "patient", "deliberate", "slight", "minor",
    "small", "modest", "plain", "bare", "empty", "hollow", "vacant", "absent",
    "distant", "remote", "near", "close", "adjacent", "parallel", "recursive",
    "repeated", "doubled", "folded", "creased", "worn", "faded", "weathered",
    "residual", "leftover", "remaining", "unanswered", "unread", "unmarked",
    "unsigned", "unnamed", "anonymous", "unwitnessed", "unrecorded", "recorded",
    "logged", "counted", "numbered", "indexed", "filed", "stored", "kept",
    "held", "withheld", "released", "open", "closed", "sealed", "locked",
    "ajar", "permeable", "porous", "transparent", "translucent", "opaque",
    "visible", "invisible", "hidden", "exposed", "latent", "dormant", "idle",
    "waiting", "pending", "queued", "buffered", "cached", "compressed",
    "expanded", "delayed", "belated", "early", "gradual", "incremental",
    "accumulated", "layered", "granular", "textured", "weightless", "light",
    "heavy", "shared",
  ],
  prepositions: [
    "into", "against", "before", "beneath", "through", "toward", "inside",
    "between", "after", "without", "with", "near", "under", "over", "above",
    "below", "beyond", "within", "among", "across", "along", "past", "behind",
    "beside", "around", "despite", "throughout", "underneath", "amid",
    "alongside",
  ],
  conjunctions: [
    "and", "or", "then", "yet", "because", "so that", "until", "while", "but",
    "nor", "so", "as", "if", "though", "although", "whereas", "since",
    "unless", "when", "where", "once", "even so", "and yet", "or else",
  ],
  sutures: [
    "— the room notes this —", "— archive holds —", "— signal received —",
    "— witness counted —", "— without name —", "— after latency —",
    "— a small consent —", "— folded once —", "— the log remembers —",
    "— address withheld —", "— no name given —", "— counted and kept —",
    "— seen, not stored —", "— a brief presence —", "— the cache forgets —",
    "— received in full —", "— the server attends —", "— marked in passing —",
    "— held a moment —", "— the page turns —", "— between two requests —",
    "— a quiet arrival —", "— nothing returned —", "— the threshold notes it —",
    "— logged without trace —", "— a partial answer —", "— consent, then silence —",
    "— the column holds —", "— after the pause —", "— witnessed once —",
    "— the record stands —", "— folded again —", "— a small latency —",
    "— the hand withdraws —", "— still counted —", "— the margin keeps it —",
    "— an address, hashed —", "— received, not read —", "— the room stays —",
    "— a visit, counted —", "— the signal fades —", "— kept for now —",
    "— the archive widens —", "— nothing withheld —", "— a breath of latency —",
    "— the door, ajar —", "— noted and released —", "— the witness departs —",
    "— a residue remains —", "— the surface answers —", "— in the interval —",
    "— a name, then none —", "— the buffer holds —", "— attention paid —",
    "— the visit ends —", "— so far, so kept —", "— another arrival —",
    "— the echo settles —", "— recorded in passing —", "— a slow consent —",
    "— the queue advances —", "— nothing forgotten yet —",
  ],
  punctuation: [".", ",", ";", "—"],
  corruption_glyphs: ["▮", "░", "▒", "▓", "◌", "◍", "◯", "⌁", "⌇", "⎓", "⎔", "⏚"],
};

export const ROLES = Object.freeze([
  "openings",
  "nouns",
  "verbs",
  "prepositions",
  "adjectives",
  "conjunctions",
  "sutures",
  "punctuation",
]);
