// Curated token pools for the body-for-visits artwork.
// Themes: visitation, enclosure, attention, request/response, memory,
// compression, witness, address, body, signal, latency, residue, consent,
// disappearance, archive, surface, server, return, threshold.
// Not buzzword soup. Tokens carry the work's tone.

export const BUCKETS = {
  openings: [
    "here",
    "again",
    "still",
    "meanwhile",
    "before that",
    "elsewhere",
    "since you arrived",
    "between requests",
    "in the margin",
    "under the cache",
  ],
  nouns: [
    "visitor",
    "witness",
    "threshold",
    "cache",
    "archive",
    "residue",
    "surface",
    "server",
    "room",
    "request",
    "response",
    "signal",
    "latency",
    "body",
    "column",
    "breath",
    "address",
    "hand",
  ],
  verbs: [
    "arrives",
    "lingers",
    "returns",
    "folds",
    "holds",
    "attends",
    "forgets",
    "remembers",
    "compresses",
    "answers",
    "withholds",
    "passes through",
    "marks",
    "keeps",
    "releases",
  ],
  prepositions: [
    "into",
    "against",
    "before",
    "beneath",
    "through",
    "toward",
    "inside",
    "between",
    "after",
    "without",
    "with",
    "near",
  ],
  adjectives: [
    "quiet",
    "attentive",
    "partial",
    "unfinished",
    "legible",
    "narrow",
    "slow",
    "late",
    "present",
    "consented",
    "seen",
    "archived",
    "nameless",
    "returning",
  ],
  conjunctions: ["and", "or", "then", "yet", "because", "so that", "until", "while"],
  sutures: [
    "— the room notes this —",
    "— archive holds —",
    "— signal received —",
    "— witness counted —",
    "— without name —",
    "— after latency —",
    "— a small consent —",
    "— folded once —",
  ],
  punctuation: [".", ",", ";", "—"],
  corruption_glyphs: ["▮", "░", "▒", "▓", "◌", "◍", "◯", "⌁", "⌇", "⎓", "⎔", "⏚"],
};

export const ROLES = Object.freeze([
  "openings",
  "nouns",
  "verbs",
  "prepositions",
  "adjectives",
  "conjunctions",
  "sutures",
  "punctuation",
]);
